-- MySQL Script generated by MySQL Workbench
-- Fri Nov  5 15:11:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tinkoff_HR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tinkoff_HR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tinkoff_HR` DEFAULT CHARACTER SET utf8 ;
USE `Tinkoff_HR` ;

-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Employees` (
  `email` VARCHAR(45) NOT NULL,
  `fio` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `photo_url` VARCHAR(100) NULL,
  `bio` VARCHAR(256) CHARACTER SET 'utf8' NULL,
  `project` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `company_position` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `birth_date` DATE NOT NULL,
  `employment_date` DATE NOT NULL,
  `table_number` VARCHAR(8) NULL,
  `status` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `achievement` VARCHAR(45) NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Products` (
  `articul` VARCHAR(6) NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `photo_url` VARCHAR(100) NULL,
  `category` VARCHAR(20) CHARACTER SET 'utf8' NULL,
  `store_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`articul`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `store_type` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Order_votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Order_votes` (
  `email` VARCHAR(45) NOT NULL,
  `articul` VARCHAR(6) NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`email`, `articul`),
  INDEX `product_id_idx` (`articul` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk6`
    FOREIGN KEY (`email`)
    REFERENCES `Tinkoff_HR`.`Employees` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk7`
    FOREIGN KEY (`articul`)
    REFERENCES `Tinkoff_HR`.`Products` (`articul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk8`
    FOREIGN KEY (`order_id`)
    REFERENCES `Tinkoff_HR`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Order_products` (
  `order_id` INT NOT NULL,
  `articul` VARCHAR(6) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `articul`),
  INDEX `product_id_idx` (`articul` ASC) VISIBLE,
  CONSTRAINT `fk4`
    FOREIGN KEY (`order_id`)
    REFERENCES `Tinkoff_HR`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk5`
    FOREIGN KEY (`articul`)
    REFERENCES `Tinkoff_HR`.`Products` (`articul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Cafes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Cafes` (
  `cafe_id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `business_lunch` VARCHAR(45) NULL,
  `average_check` FLOAT NULL,
  PRIMARY KEY (`cafe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Cafe_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Cafe_reviews` (
  `user_email` VARCHAR(45) NOT NULL,
  `cafe_id` INT NOT NULL,
  `pros` TINYTEXT NULL,
  `cons` TINYTEXT NULL,
  `rating` INT NOT NULL,
  INDEX `cafe_id_idx` (`cafe_id` ASC) VISIBLE,
  PRIMARY KEY (`user_email`, `cafe_id`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`cafe_id`)
    REFERENCES `Tinkoff_HR`.`Cafes` (`cafe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2`
    FOREIGN KEY (`user_email`)
    REFERENCES `Tinkoff_HR`.`Employees` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Cafe_suggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Cafe_suggestions` (
  `suggestion_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `cafe_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`suggestion_id`),
  INDEX `user_email_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk3`
    FOREIGN KEY (`user_email`)
    REFERENCES `Tinkoff_HR`.`Employees` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Meeting_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Meeting_rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Slots` (
  `slot_number` INT NOT NULL,
  `slot_start` TIME NOT NULL,
  `slot_end` TIME NOT NULL,
  PRIMARY KEY (`slot_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Reservations` (
  `reservetion_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `slot_number` INT NOT NULL,
  PRIMARY KEY (`reservetion_id`),
  INDEX `room_id_idx` (`room_id` ASC) VISIBLE,
  INDEX `slot_number_idx` (`slot_number` ASC) VISIBLE,
  CONSTRAINT `fk9`
    FOREIGN KEY (`room_id`)
    REFERENCES `Tinkoff_HR`.`Meeting_rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk10`
    FOREIGN KEY (`slot_number`)
    REFERENCES `Tinkoff_HR`.`Slots` (`slot_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tinkoff_HR`.`Reserved_by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tinkoff_HR`.`Reserved_by` (
  `recervation_id` INT NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recervation_id`, `user_email`),
  INDEX `user_email_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk11`
    FOREIGN KEY (`recervation_id`)
    REFERENCES `Tinkoff_HR`.`Reservations` (`reservetion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk12`
    FOREIGN KEY (`user_email`)
    REFERENCES `Tinkoff_HR`.`Employees` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
